best_args = {'seq-cifar10': {'trire': {200: {'lr': 0.03,
                                            'e_lambda': 10,
                                            'gamma': 0,
                                            'minibatch_size': 32,
                                            'alpha': 0.1,
                                            'beta': 1,
                                            'batch_size': 32,
                                            'n_epochs': 50}}},
             'seq-cifar100': {'trire': {200: {'lr': 0.03,
                                             'e_lambda': 10,
                                             'gamma': 0,
                                             'minibatch_size': 32,
                                             'alpha': 0.2,
                                             'beta': 1,
                                             'batch_size': 32,
                                             'n_epochs': 50}}},

             'seq-tinyimg': {'trire': {200: {'lr': 0.03,
                                            'e_lambda': 10,
                                            'gamma': 0,
                                            'minibatch_size': 32,
                                            'alpha': 0.2,
                                            'beta': 1,
                                            'batch_size': 32,
                                            'n_epochs': 50}}}}
